# Generated by Django 3.2.3 on 2021-06-15 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veille',
            fields=[
                ('Nom', models.CharField(max_length=55)),
                ('Prenom', models.CharField(max_length=55, unique=True)),
                ('Date_de_naissance', models.DateField(auto_now_add=True)),
                ('Email', models.CharField(max_length=55)),
                ('Confirmation_email', models.EmailField(max_length=55, primary_key=True, serialize=False, unique=True)),
                ('Mot_de_passe', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requette', models.CharField(max_length=155)),
                ('date_req', models.DateField(auto_now=True)),
                ('Email', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='veille.veille')),
            ],
        ),
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_auteur', models.CharField(max_length=55)),
                ('Domaine', models.CharField(max_length=55)),
                ('Mot_cle1', models.CharField(max_length=25)),
                ('Mot_cle2', models.CharField(max_length=25)),
                ('Mot_cle3', models.CharField(max_length=25)),
                ('date_req', models.DateField(auto_now=True)),
                ('Email', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='veille.veille')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_article', models.CharField(max_length=70)),
                ('lien_site', models.CharField(max_length=70)),
                ('lien_document', models.CharField(max_length=70)),
                ('abstract', models.CharField(default="N'est pas disponible", max_length=500)),
                ('date_article', models.DateField(auto_now=True)),
                ('nouveau', models.CharField(default=0, max_length=10)),
                ('Email', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='veille.veille')),
            ],
        ),
    ]
